### ISSUE TITLE
Implement contract to integrate with Solv Finance

### ISSUE THREAD

**Issue by baonguyen1904** [harmonixfi/core-smart-contract#143]

**Comment by vuxbasnin** [comment]
SolvVault:
- No performance fees
- Asset token current is only wbtc
- Flow(method name):
+ deposit: user deposit to the SolvVault => SolvVault will call subscribe to intergration with Solv => Solv will mint for Vault a NFT(GOEFR). One user only have one token GOEFR util request redeem all shares.
+ initiateWithdrawal: create request withdrawal with shares of user want to withdrawal => intergration with Solv with method requestRedeem. Solv will burn token GOEFR of user if user request redeem all shares to mint a another token is GOEFS(used in claim), if not GOEFR still exist in SolvVault(GOEFS same like this).
+ redeem: user call this method to claim token from Solv to SolvVault => SolvVault when transfer to vault of user with balance corresponding.
